/**
 * Public entrypoint for shared API types.
 *
 * `openapi.ts` is generated by `pnpm gen:types` (FastAPI -> openapi.json ->
 * openapi-typescript) and is gitignored. The hand-maintained shapes below are a
 * stable fallback so the web app compiles even before codegen has run (e.g. on a
 * fresh clone in CI). Prefer importing from "./openapi" once it exists.
 */

export interface WhoAmI {
  user_id: string;
  tenant_id: string;
  email: string;
  role: string;
}

export interface TokenResponse {
  access_token: string;
  token_type: string;
}
